# Coolify Configuration for Grünerator Chat
# https://coolify.io/docs/knowledge-base/docker/compose-file

services:
  chat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3210:3210'
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "require('http').get('http://localhost:3210/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3210
      - HOSTNAME=0.0.0.0
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - MCP_URL=${MCP_URL}
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
            - NEXT_PUBLIC_AUTH_DISABLED=${NEXT_PUBLIC_AUTH_DISABLED:-false}

labels:
  coolify.managed: 'true'
  coolify.name: 'gruenerator-chat'
  coolify.http.port: '3210'
